### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by joemouth** [cosmocode/dokuwiki-plugin-imgpaste#1]
A very useful plugin, but nothing happens with Strg-V in edit mode

Image in clipboard, tested with Ctrl-V in IrfanView.
How can I fix this?

```
Google Chrome portable V 27.x
DokuWiki version: Release 2013-05-10 “Weatherwax”
```

May be a https://... issue?

Same situation on other system.

**Comment by ab-tools** [comment]
Same for me:
Tested with Chrome 46 and nothing happens.

So this plug-in seems not to work at all - even more than 2 years after this issue was created...

**Comment by An-dir** [comment]
Didn't work for me after Plugin "Fastwiki" was enabled. So i disabled it, and it works again. Check if any other plugin you have enabled doesn't work together with "imgpaste".
What i noticed while testing, was that "Fastwiki" and "imgpaste" work together only one time, if i uninstall and reinstall the "imgpaste" plugin.

**Comment by patrickruppelt** [comment]
Indeed, disabling Fastwiki kind of 'solves' the issue. Will give it a try and see which plugin I can give up on more easily.
