### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by amercier** [cosmocode/dokuwiki-plugin-imgpaste#2]
That would be a great enhancement to make it work on Firefox. I think this is definitely possible. [PasteBoard](http://pasteboard.co/) is doing it (see https://github.com/JoelBesada/pasteboard/blob/master/assets/js/modules/copyandpaste.coffee for details) so I think this is definitely possible.

**Comment by Klap-in** [comment]
Suggestion at the old DokuWiki issue tracker [FS#2865](https://bugs.dokuwiki.org/index.php?do=details&task_id=2865) for an uploader : https://github.com/FineUploader/fine-uploader
Javascript solution, that suggest to be cross browser.

**Comment by proxymus** [comment]
I would prefer browser independence like it is the case with FinUploader.

**Comment by drogenlied** [comment]
From Firefox 50 onwards, this should be fixable or actually fixed:
https://bugzilla.mozilla.org/show_bug.cgi?id=891247
https://bugzilla.mozilla.org/show_bug.cgi?id=906420

**Comment by drogenlied** [comment]
Ok, I tested this with FF50 beta 7 on Windows 8.1 and the 2012 release of dokuwiki and it works!
