### ISSUE TITLE
Edge compatibility

### ISSUE THREAD

**Issue by landrix** [cosmocode/dokuwiki-plugin-imgpaste#26]
Does the plugin also work with Edge? (It doesn't work for me, I just want to make sure it's not the plugin)

**Comment by splitbrain** [comment]
I don't know. I would assume it does, since Edge is relatively modern. Do you get any errors in the JavaScript console?

**Comment by landrix** [comment]
It seems to be a template issue

https://github.com/IceWreck/Argon-Dokuwiki-Template/issues/50
