### ISSUE TITLE
Not working on Chrome or Firefox

### ISSUE THREAD

**Issue by GuiguiAko** [cosmocode/dokuwiki-plugin-imgpaste#30]
Hi,
We struggling with the plugin, it's never worked and don't know why.

We used the version of dokuwiki Release 2023-04-04a "Jack Jackrum"

Chrome is up to date, firefox too.

The plugin was installed with plugin manager, the version of the plugin is 2023-02-08 #

**Comment by splitbrain** [comment]
no info given

**Comment by GuiguiAko** [comment]
Sorry, we can't copy paste with ctrl V or anything, we search in console mode and nothing appear, no error, anything
