### ISSUE TITLE
It throw wrong msg by chinese @ID@

### ISSUE THREAD

**Issue by 7SevenW** [cosmocode/dokuwiki-plugin-imgpaste#5]
![image](https://cloud.githubusercontent.com/assets/14065101/9732190/6f557764-5654-11e5-97cb-07c59a436ecb.png)

I have set fnencode with "safe".When I used this plugin with  "@ID@" param, i got this msg.It seems work bad with “unsafe page id”

**Comment by lc237423551** [comment]
Has your problem been solved?

**Comment by lc237423551** [comment]
> ![image](https://cloud.githubusercontent.com/assets/14065101/9732190/6f557764-5654-11e5-97cb-07c59a436ecb.png)
> 
> I have set fnencode with "safe".When I used this plugin with "@id@" param, i got this msg.It seems work bad with “unsafe page id”
Has your problem been solved?

**Comment by splitbrain** [comment]
I can't reproduce this. Works fine with a chinese namespace in my test.
